// Generated by CoffeeScript 1.8.0
(function() {
  var Fizzbuzz;

  Fizzbuzz = (function() {
    function Fizzbuzz() {}

    Fizzbuzz.prototype.isDivisibleByThree = function(number) {
      return this.isDivisibleBy(3, number);
    };

    Fizzbuzz.prototype.isDivisibleByFive = function(number) {
      return this.isDivisibleBy(5, number);
    };

    Fizzbuzz.prototype.isDivisibleByFifteen = function(number) {
      return this.isDivisibleBy(15, number);
    };

    Fizzbuzz.prototype.says = function(number) {
      if (this.isDivisibleByFifteen(number)) {
        return "Fizzbuzz";
      } else if (this.isDivisibleByThree(number)) {
        return "Fizz";
      } else if (this.isDivisibleByFive(number)) {
        return "Buzz";
      } else {
        return number;
      }
    };

    Fizzbuzz.prototype.isDivisibleBy = function(divisor, number) {
      return number % divisor === 0;
    };

    return Fizzbuzz;

  })();

  module.exports = Fizzbuzz;

}).call(this);
